import type { IcpProfile, SyntheticProspect } from './types';

export const demoNotice =
  'Synthetic demo data only. No real companies, contacts, scraping, outreach, or live research are used.';

export const icpProfile: IcpProfile = {
  name: 'AI Enablement Group SMB Prospect Research ICP',
  companySizeRange: '75–250 employees',
  targetIndustries: [
    'Managed services',
    'Home services',
    'Specialty manufacturing',
    'Healthcare services',
    'B2B distribution',
  ],
  targetRegions: ['United States', 'Philippines support operations', 'Remote-friendly teams'],
  priorityPainPoints: [
    'Manual prospect research and inconsistent qualification',
    'Sales teams spending too much time preparing before discovery',
    'Operational knowledge spread across spreadsheets, inboxes, and tribal memory',
    'Weak handoffs between intake, operations, and revenue teams',
  ],
  buyingSignals: [
    'Recent growth in sales or operations headcount',
    'New process-improvement initiative',
    'High volume of inbound inquiries or quote requests',
    'Visible need for faster research, better prioritization, or cleaner handoffs',
  ],
  disqualifiers: [
    'Company appears too small for workflow leverage',
    'No clear operational pain signal',
    'Highly regulated workflow requiring deeper compliance review before demo-stage qualification',
    'Request appears focused on fully automated outreach rather than human-reviewed research',
  ],
};

const makeTrail = (
  used: string[],
  inferred: string[],
  requiresHumanReview: string[],
  output: string,
) => [
  {
    step: 'Synthetic profile reviewed',
    used,
    inferred,
    requiresHumanReview,
    output,
  },
];

export const syntheticProspects: SyntheticProspect[] = [
  {
    id: 'brightpath-dental',
    companyName: 'BrightPath Dental Group',
    industry: 'Healthcare services',
    region: 'Southeast United States',
    employeeCount: 180,
    summary: 'Fictitious multi-location dental services group with centralized intake and office-level follow-up workflows.',
    painSignals: ['Split inquiry intake across phone, web forms, and callbacks.', 'Handoff friction between central operations and local offices.', 'Revenue depends on fast response and consistent follow-up.'],
    buyingSignals: ['Recent expansion into additional markets.', 'Centralized operations model.', 'Clear response-time value.'],
    possibleUseCases: ['Inquiry triage', 'Intake note standardization', 'Follow-up readiness checklist'],
    aiResearchSummary: 'Simulated AI summary: BrightPath looks like a strong fit because it has enough operational scale, repeatable intake workflows, and clear revenue impact from faster review and cleaner handoffs.',
    fitScore: 88,
    confidenceScore: 82,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Confirm whether intake data is centralized before assuming workflow scope.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: validate intake workflow and ownership.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 19, painPointFit: 22, buyingSignalFit: 21, operationalComplexity: 13, riskPenalty: -5 },
    researchBrief: {
      companySnapshot: 'Fictitious 180-person dental services group operating across multiple local offices with centralized intake support.',
      businessModel: 'Patient inquiry intake, appointment routing, local office follow-up, and recurring care relationships.',
      likelyOperationalPain: ['Inconsistent intake notes across channels.', 'Central team and local offices may duplicate follow-up work.', 'Slow response can reduce appointment conversion.'],
      aiOpportunity: ['Summarize inquiries into consistent human-review packets.', 'Flag urgency, location, and service type before handoff.', 'Help reviewers prioritize high-value inquiries faster.'],
      suggestedDiscoveryQuestions: ['Where do new patient inquiries arrive today?', 'Who owns the handoff from central intake to local offices?', 'What information is most often missing before follow-up?', 'How do you measure response time and appointment conversion?'],
      recommendedNextStep: 'Schedule workflow discovery focused on intake routing, office handoff, and response-time bottlenecks.',
      humanValidationNeeded: ['Actual intake channels', 'Ownership of follow-up decisions', 'Privacy and data-handling boundaries'],
    },
    auditTrail: makeTrail(['Industry', 'employee count', 'multi-location model'], ['Likely intake routing friction'], ['Centralized intake ownership'], 'High Fit with 88 fit score and 82 confidence score.'),
  },
  {
    id: 'harborpoint-manufacturing',
    companyName: 'HarborPoint Manufacturing',
    industry: 'Specialty manufacturing',
    region: 'Midwest United States',
    employeeCount: 210,
    summary: 'Fictitious specialty manufacturer with custom quote requests and engineering review before sales follow-up.',
    painSignals: ['Custom requests need manual review before qualification.', 'Sales and engineering handoffs slow quote readiness.', 'Technical resources can be pulled into weak-fit opportunities.'],
    buyingSignals: ['High-friction quoting workflow.', 'Cross-functional qualification.', 'Need for structured qualification notes.'],
    possibleUseCases: ['Quote-intake classification', 'Technical-fit triage', 'Qualification summary'],
    aiResearchSummary: 'Simulated AI summary: HarborPoint is a strong fit because custom manufacturing inquiries often require structured triage before sales or engineering time is used.',
    fitScore: 91,
    confidenceScore: 78,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Data Gap', text: 'The demo profile does not confirm current quote-management tools.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: validate quoting bottleneck before recommending use case.',
    scoringBreakdown: { industryFit: 20, companySizeFit: 20, painPointFit: 24, buyingSignalFit: 22, operationalComplexity: 14, riskPenalty: -9 },
    researchBrief: {
      companySnapshot: 'Fictitious 210-person specialty manufacturer with custom quote requests that require technical review.',
      businessModel: 'Project-based product sales, custom quoting, engineering input, and sales-led follow-up.',
      likelyOperationalPain: ['Sales may lack enough technical context to qualify requests quickly.', 'Engineering review time can be wasted on weak-fit opportunities.', 'Quote-readiness criteria may vary by reviewer.'],
      aiOpportunity: ['Classify quote requests by fit, urgency, and technical complexity.', 'Prepare a structured brief before engineering review.', 'Highlight missing details needed before a quote can move forward.'],
      suggestedDiscoveryQuestions: ['What makes a quote request worth engineering review?', 'Which missing details slow quote preparation most often?', 'How are sales and engineering handoffs documented today?', 'Where does the qualification decision usually break down?'],
      recommendedNextStep: 'Run a discovery session on quote intake, technical-fit criteria, and sales-engineering handoffs.',
      humanValidationNeeded: ['Current quote intake process', 'Technical review criteria', 'Systems used for quote tracking'],
    },
    auditTrail: makeTrail(['Custom quote context', 'employee count', 'sales-engineering handoff clue'], ['Manual qualification likely consumes technical staff time'], ['Current quoting process and required fields'], 'Prospect advanced to high-fit scoring review.'),
  },
  {
    id: 'sunriver-home-services',
    companyName: 'SunRiver Home Services',
    industry: 'Home services',
    region: 'Florida',
    employeeCount: 95,
    summary: 'Fictitious regional home-services company with field teams, inbound service requests, and seasonal demand spikes.',
    painSignals: ['Volume spikes make manual inquiry prioritization difficult.', 'Dispatch and sales follow-up compete for attention.', 'Slow follow-up can directly affect revenue.'],
    buyingSignals: ['Regional scale above owner-operator stage.', 'Repeatable inquiry qualification workflow.', 'Clear business value from faster response.'],
    possibleUseCases: ['Service-request triage', 'Inquiry urgency scoring', 'Handoff summary'],
    aiResearchSummary: 'Simulated AI summary: SunRiver appears to be a good fit because urgency, geography, and job type likely affect prospect priority.',
    fitScore: 81,
    confidenceScore: 74,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Weak Signal', text: 'Inquiry volume is inferred from company type and size, not confirmed.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm inquiry volume and seasonality.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 17, painPointFit: 20, buyingSignalFit: 18, operationalComplexity: 11, riskPenalty: -3 },
    researchBrief: {
      companySnapshot: 'Fictitious 95-person regional home-services operator with field teams and inbound service requests.',
      businessModel: 'Local service inquiries, dispatch coordination, field operations, and repeat customer relationships.',
      likelyOperationalPain: ['Urgent requests may not be prioritized consistently.', 'Dispatch and sales details may be captured in different places.', 'Seasonal spikes can create response delays.'],
      aiOpportunity: ['Score service requests by urgency, location, and revenue potential.', 'Create a reviewer-ready summary before dispatch or sales follow-up.', 'Flag missing job details before a team member spends time chasing context.'],
      suggestedDiscoveryQuestions: ['Which service requests need the fastest response?', 'How do dispatch and sales share context today?', 'What happens when inquiry volume spikes?', 'Which job details are most often missing at intake?'],
      recommendedNextStep: 'Validate inquiry volume and map the service-request handoff from intake to dispatch or sales.',
      humanValidationNeeded: ['Actual inquiry volume', 'Seasonality pattern', 'Dispatch handoff process'],
    },
    auditTrail: makeTrail(['Home services category', 'regional operating model', '95 employees'], ['Seasonal inquiry-volume spikes'], ['Actual inbound volume and dispatch process'], 'Prospect scored as high fit with moderate confidence.'),
  },
  {
    id: 'northstar-logistics',
    companyName: 'Northstar Logistics Partners',
    industry: 'Logistics services',
    region: 'United States / Philippines support desk',
    employeeCount: 240,
    summary: 'Fictitious logistics services company with distributed operations and internal support coordination across time zones.',
    painSignals: ['Distributed teams may create inconsistent account notes.', 'Operational exceptions distract sales and account teams.', 'Prospect and account context may be fragmented across systems.'],
    buyingSignals: ['Cross-time-zone support model.', 'Operational complexity creates need for structured summaries.', 'Potential value from cleaner qualification and handoffs.'],
    possibleUseCases: ['Prospect-to-account context summary', 'Internal handoff assistant', 'Field completion support'],
    aiResearchSummary: 'Simulated AI summary: Northstar is a medium fit because the strongest use case may be internal context capture rather than pure prospect qualification.',
    fitScore: 76,
    confidenceScore: 68,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'ICP Mismatch', text: 'The strongest use case may be internal handoff improvement rather than prospect qualification.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: clarify whether revenue or operations owns the problem.',
    scoringBreakdown: { industryFit: 13, companySizeFit: 20, painPointFit: 19, buyingSignalFit: 16, operationalComplexity: 15, riskPenalty: -7 },
    researchBrief: {
      companySnapshot: 'Fictitious 240-person logistics services firm with distributed support across time zones.',
      businessModel: 'Operational service delivery, account coordination, exception handling, and revenue team handoffs.',
      likelyOperationalPain: ['Support and account context may not be visible to revenue teams.', 'Exceptions can pull attention away from growth work.', 'Distributed teams may use inconsistent notes and handoff language.'],
      aiOpportunity: ['Create structured handoff summaries from fragmented context.', 'Flag whether the use case belongs to sales, account management, or operations.', 'Reduce reviewer time spent reconstructing account history.'],
      suggestedDiscoveryQuestions: ['Who owns the context handoff today?', 'Where do support exceptions get documented?', 'Which team loses the most time recreating context?', 'Is the business pain tied to revenue growth or operations quality?'],
      recommendedNextStep: 'Hold until ownership is clarified; then scope either revenue handoff or operations-support workflow discovery.',
      humanValidationNeeded: ['Revenue owner versus operations owner', 'Where account context lives', 'Impact on sales or retention outcomes'],
    },
    auditTrail: makeTrail(['Distributed support model', 'employee count', 'operations context'], ['Context and handoff friction'], ['Revenue owner versus operations owner'], 'Prospect placed on Hold pending human review.'),
  },
  {
    id: 'clearwater-senior-care',
    companyName: 'Clearwater Senior Care Network',
    industry: 'Healthcare services',
    region: 'Carolinas',
    employeeCount: 155,
    summary: 'Fictitious senior-care provider network with family inquiries, intake qualification, and location-level admissions follow-up.',
    painSignals: ['Inquiry quality varies by location.', 'Family intake requires careful handoff notes.', 'Delayed follow-up can affect admissions conversion.'],
    buyingSignals: ['Multi-site care model.', 'High-value intake workflow.', 'Need for consistent handoff documentation.'],
    possibleUseCases: ['Intake summary generation', 'Location routing guidance', 'Admission-readiness notes'],
    aiResearchSummary: 'Simulated AI summary: Clearwater is a strong fit because inquiry quality, urgency, and location routing create a practical human-reviewed qualification use case.',
    fitScore: 86,
    confidenceScore: 76,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Healthcare-adjacent workflows require confirmation of privacy and compliance boundaries.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm privacy boundaries and intake ownership.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 18, painPointFit: 22, buyingSignalFit: 20, operationalComplexity: 13, riskPenalty: -5 },
    researchBrief: {
      companySnapshot: 'Fictitious 155-person senior-care network with family inquiries, intake qualification, and admissions follow-up.',
      businessModel: 'Family inquiry intake, location routing, admissions support, and care-program matching.',
      likelyOperationalPain: ['Families may provide incomplete or emotional inquiry details.', 'Location-level follow-up can vary in quality.', 'Admissions teams need consistent intake context without overstepping privacy boundaries.'],
      aiOpportunity: ['Summarize family inquiries for human review.', 'Route inquiries by location, urgency, and care needs.', 'Flag privacy-sensitive areas that require human handling.'],
      suggestedDiscoveryQuestions: ['What intake information can be safely summarized?', 'Which locations receive the highest inquiry volume?', 'What details are needed before admissions follow-up?', 'Who reviews privacy and compliance boundaries?'],
      recommendedNextStep: 'Validate privacy boundaries first, then map intake routing and admissions handoff.',
      humanValidationNeeded: ['Privacy requirements', 'Admissions workflow ownership', 'Approved data handling boundaries'],
    },
    auditTrail: makeTrail(['Care network model', 'employee count', 'intake context'], ['Inquiry routing and admission handoff friction'], ['Privacy boundaries and intake systems'], 'Prospect scored High Fit with compliance review flag.'),
  },
  {
    id: 'bluepeak-managed-services',
    companyName: 'BluePeak Managed Services',
    industry: 'Managed services',
    region: 'Texas',
    employeeCount: 130,
    summary: 'Fictitious managed services firm with inbound support requests, sales discovery calls, and account expansion opportunities.',
    painSignals: ['Sales and support signals may live in separate systems.', 'Discovery notes may not consistently reach account teams.', 'Follow-up quality affects expansion opportunities.'],
    buyingSignals: ['Service desk and revenue handoff overlap.', 'Likely documentation pressure.', 'Repeatable qualification and account review workflow.'],
    possibleUseCases: ['Call summary', 'Expansion signal scoring', 'Support-to-sales handoff notes'],
    aiResearchSummary: 'Simulated AI summary: BluePeak is a strong fit because managed services firms often need cleaner handoffs between support, account management, and sales.',
    fitScore: 84,
    confidenceScore: 80,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Weak Signal', text: 'Exact ticketing and account tools are not confirmed in the synthetic profile.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm support and account-management workflow.',
    scoringBreakdown: { industryFit: 20, companySizeFit: 18, painPointFit: 20, buyingSignalFit: 19, operationalComplexity: 11, riskPenalty: -4 },
    researchBrief: {
      companySnapshot: 'Fictitious 130-person managed services firm with support, account management, and sales handoffs.',
      businessModel: 'Recurring managed services, support desk activity, account expansion, and sales-led discovery.',
      likelyOperationalPain: ['Support signals may not reach sales or account managers quickly.', 'Discovery notes may be inconsistent.', 'Expansion opportunities can get buried in service conversations.'],
      aiOpportunity: ['Turn support and discovery context into structured reviewer briefs.', 'Flag potential expansion signals for human review.', 'Standardize handoff notes between support, account, and sales teams.'],
      suggestedDiscoveryQuestions: ['Where do expansion signals show up first?', 'How are support-to-sales handoffs handled today?', 'Which notes are most useful to account managers?', 'How often are opportunities missed because context is fragmented?'],
      recommendedNextStep: 'Validate support-to-sales handoff and account-review workflow before recommending a pilot.',
      humanValidationNeeded: ['Ticketing workflow', 'Account ownership model', 'Expansion signal criteria'],
    },
    auditTrail: makeTrail(['Managed services category', 'support and sales context'], ['Support-to-sales handoff friction'], ['Current ticketing and account tools'], 'Prospect scored High Fit for revenue-workflow review.'),
  },
  {
    id: 'summit-trade-supply',
    companyName: 'Summit Trade Supply',
    industry: 'B2B distribution',
    region: 'Mountain West',
    employeeCount: 115,
    summary: 'Fictitious B2B trade supplier with contractor accounts, quote requests, and recurring reorders.',
    painSignals: ['Quote requests may arrive with incomplete job context.', 'Account history may not be visible during qualification.', 'Sales follow-up depends on clean product and job notes.'],
    buyingSignals: ['B2B account workflow.', 'Repeat quote and reorder activity.', 'Clear value from better account-context summaries.'],
    possibleUseCases: ['Quote request summarization', 'Account context lookup', 'Next-step notes'],
    aiResearchSummary: 'Simulated AI summary: Summit is a strong fit because distribution workflows often benefit from faster quote triage and better account-context handoffs.',
    fitScore: 83,
    confidenceScore: 73,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Data Gap', text: 'Current quote-management process is not confirmed.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: verify quote volume and account-history process.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 18, painPointFit: 20, buyingSignalFit: 19, operationalComplexity: 12, riskPenalty: -4 },
    researchBrief: {
      companySnapshot: 'Fictitious 115-person B2B trade supplier handling contractor accounts, quote requests, and recurring reorders.',
      businessModel: 'Contractor account sales, quote intake, reorder support, and product availability coordination.',
      likelyOperationalPain: ['Quote requests may lack product, job, or timing details.', 'Account history may not be surfaced during qualification.', 'Follow-up quality depends on clean job notes.'],
      aiOpportunity: ['Summarize quote requests into reviewer-ready packets.', 'Flag missing job details before sales follow-up.', 'Surface likely account-context questions for the reviewer.'],
      suggestedDiscoveryQuestions: ['What information is usually missing in quote requests?', 'How does the team check account history before follow-up?', 'Which requests require the fastest response?', 'Where do quote notes get stored today?'],
      recommendedNextStep: 'Validate quote intake volume and account-history access before scoping a pilot.',
      humanValidationNeeded: ['Quote volume', 'Account-history process', 'Product and job detail requirements'],
    },
    auditTrail: makeTrail(['B2B distribution model', 'quote request context'], ['Incomplete quote data and account context gaps'], ['Quote volume and account-history usage'], 'Prospect scored High Fit for quote-preparation workflow.'),
  },
  {
    id: 'cedarworks-construction',
    companyName: 'CedarWorks Construction',
    industry: 'Construction services',
    region: 'Georgia',
    employeeCount: 140,
    summary: 'Fictitious construction services firm with project inquiries, bid qualification, and field-office coordination.',
    painSignals: ['Project inquiries need fast fit checks.', 'Bid notes may be inconsistent across offices.', 'Field and sales teams may duplicate qualification work.'],
    buyingSignals: ['Project-based sales workflow.', 'Multi-office coordination.', 'Need for consistent qualification criteria.'],
    possibleUseCases: ['Project-fit scoring', 'Bid intake summary', 'Handoff checklist'],
    aiResearchSummary: 'Simulated AI summary: CedarWorks is a medium fit because bid qualification is useful, but the workflow may require more industry-specific scoping before implementation.',
    fitScore: 72,
    confidenceScore: 66,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Construction bidding workflows may need more detailed process mapping before qualification.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm bid workflow and project-fit criteria.',
    scoringBreakdown: { industryFit: 12, companySizeFit: 18, painPointFit: 18, buyingSignalFit: 16, operationalComplexity: 13, riskPenalty: -5 },
    researchBrief: {
      companySnapshot: 'Fictitious 140-person construction services firm with project inquiries and bid qualification needs.',
      businessModel: 'Project-based sales, bid qualification, office coordination, and field execution planning.',
      likelyOperationalPain: ['Project-fit criteria may vary by office.', 'Bid details may be incomplete at intake.', 'Field and sales teams may duplicate early qualification work.'],
      aiOpportunity: ['Prepare structured bid-intake summaries for human review.', 'Flag missing project-fit details.', 'Help reviewers apply consistent qualification criteria.'],
      suggestedDiscoveryQuestions: ['What makes a project worth bidding?', 'Which bid details are most often missing?', 'Who decides whether a project is a fit?', 'How do field and sales teams share project context?'],
      recommendedNextStep: 'Hold until bid workflow and project-fit criteria are mapped in more detail.',
      humanValidationNeeded: ['Bid qualification rules', 'Office-level workflow differences', 'Field-sales handoff process'],
    },
    auditTrail: makeTrail(['Project inquiry model', 'multi-office context'], ['Bid qualification friction'], ['Bid process and project-fit fields'], 'Prospect placed on Hold pending workflow review.'),
  },
  {
    id: 'orchid-valley-hospitality',
    companyName: 'Orchid Valley Hospitality',
    industry: 'Hospitality services',
    region: 'Nevada',
    employeeCount: 185,
    summary: 'Fictitious hospitality group with event inquiries, group bookings, and location-specific sales follow-up.',
    painSignals: ['Group inquiries need routing and prioritization.', 'Event details may be incomplete at intake.', 'Local teams may follow up inconsistently.'],
    buyingSignals: ['Multi-location service model.', 'High-value inquiry workflow.', 'Clear human-review need before outreach.'],
    possibleUseCases: ['Event inquiry scoring', 'Location routing support', 'Booking summary'],
    aiResearchSummary: 'Simulated AI summary: Orchid Valley is a medium fit because the workflow has revenue value, but the use case may sit outside the highest-priority ICP industries.',
    fitScore: 69,
    confidenceScore: 69,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'ICP Mismatch', text: 'Hospitality is adjacent to the ICP but not one of the top target industries.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: decide whether hospitality belongs in this ICP for the demo.',
    scoringBreakdown: { industryFit: 10, companySizeFit: 19, painPointFit: 17, buyingSignalFit: 17, operationalComplexity: 12, riskPenalty: -6 },
    researchBrief: {
      companySnapshot: 'Fictitious 185-person hospitality group with event inquiries and group-booking follow-up.',
      businessModel: 'Multi-location hospitality services, event booking, group inquiry handling, and local sales follow-up.',
      likelyOperationalPain: ['Event details may arrive incomplete.', 'Routing to the right location or team may slow response.', 'Local follow-up quality may vary.'],
      aiOpportunity: ['Summarize event inquiries for human review.', 'Flag missing event details before follow-up.', 'Route inquiries by location, event type, and likely value.'],
      suggestedDiscoveryQuestions: ['Which event details are required before follow-up?', 'Who routes group inquiries today?', 'How often do local teams miss or delay follow-up?', 'Is hospitality a strategic ICP expansion area?'],
      recommendedNextStep: 'Hold until ICP fit is confirmed; then evaluate event inquiry routing as an adjacent workflow.',
      humanValidationNeeded: ['ICP fit decision', 'Event inquiry volume', 'Routing ownership'],
    },
    auditTrail: makeTrail(['Hospitality event inquiry model', 'employee count'], ['Group booking routing friction'], ['ICP fit decision'], 'Prospect placed on Hold due to ICP-adjacent status.'),
  },
  {
    id: 'evergreen-specialty-foods',
    companyName: 'Evergreen Specialty Foods',
    industry: 'Specialty foods distribution',
    region: 'Pacific Northwest',
    employeeCount: 65,
    summary: 'Fictitious specialty foods distributor with a smaller team and mixed retail, wholesale, and hospitality customers.',
    painSignals: ['Customer segments may require different qualification paths.', 'Order and prospect data may be spread across simple tools.', 'Smaller team may have limited bandwidth for process change.'],
    buyingSignals: ['Possible need for customer segmentation.', 'Repeatable qualification could help if volume is high enough.'],
    possibleUseCases: ['Customer-segment classification', 'Inquiry summary drafting', 'Manual cleanup checklist'],
    aiResearchSummary: 'Simulated AI summary: Evergreen may benefit from AI-assisted classification, but it is below the preferred employee-size range.',
    fitScore: 58,
    confidenceScore: 70,
    scoreBand: 'Low Fit',
    riskFlags: [{ severity: 'High', category: 'ICP Mismatch', text: 'Company size is below the preferred ICP range for this demo workflow.' }],
    recommendedAction: 'Disqualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: likely too small unless prospect volume is unusually high.',
    scoringBreakdown: { industryFit: 13, companySizeFit: 7, painPointFit: 14, buyingSignalFit: 12, operationalComplexity: 8, riskPenalty: -6 },
    researchBrief: {
      companySnapshot: 'Fictitious 65-person specialty foods distributor with mixed retail, wholesale, and hospitality customers.',
      businessModel: 'Food distribution, customer segmentation, recurring orders, and small-team sales operations.',
      likelyOperationalPain: ['Customer segments may be handled inconsistently.', 'Small teams may rely on simple tools and informal process knowledge.', 'Process improvement value may be limited by scale.'],
      aiOpportunity: ['Classify inquiries by customer segment.', 'Draft simple inquiry summaries for human review.', 'Identify whether volume justifies a larger workflow investment.'],
      suggestedDiscoveryQuestions: ['How many new inquiries arrive each week?', 'Which customer segments require different handling?', 'What tools hold customer and order context today?', 'Would the workflow save enough time to justify implementation?'],
      recommendedNextStep: 'Disqualify for now unless human review confirms unusually high volume or strategic value.',
      humanValidationNeeded: ['Actual inquiry volume', 'Strategic fit', 'Operational bandwidth for change'],
    },
    auditTrail: makeTrail(['65 employee count', 'mixed customer base'], ['Limited scale for full workflow implementation'], ['Actual prospect volume'], 'Prospect marked Low Fit and recommended for disqualification.'),
  },
];
