import type { IcpProfile, SyntheticLead } from './types';

export const demoNotice =
  'Synthetic demo data only. No real companies, contacts, CRM records, scraping, or outreach are used.';

export const icpProfile: IcpProfile = {
  name: 'AI Enablement Group SMB Revenue Operations ICP',
  companySizeRange: '75–250 employees',
  targetIndustries: [
    'Managed services',
    'Home services',
    'Specialty manufacturing',
    'Healthcare services',
    'B2B distribution',
  ],
  targetRegions: ['United States', 'Philippines support operations', 'Remote-friendly teams'],
  priorityPainPoints: [
    'Manual lead research and inconsistent qualification',
    'CRM records missing context and next-step guidance',
    'Sales teams spending too much time preparing before outreach',
    'Operational knowledge spread across spreadsheets, inboxes, and tribal memory',
  ],
  buyingSignals: [
    'Recent growth in sales or operations headcount',
    'New CRM or process-improvement initiative',
    'High volume of inbound inquiries or quote requests',
    'Visible need for faster research, better prioritization, or cleaner handoffs',
  ],
  disqualifiers: [
    'Company appears too small for workflow leverage',
    'No clear operational pain signal',
    'Highly regulated workflow requiring deeper compliance review before demo-stage qualification',
    'Request appears focused on fully automated outreach rather than human-reviewed qualification',
  ],
};

const makeTrail = (
  used: string[],
  inferred: string[],
  requiresHumanReview: string[],
  output: string,
) => [
  {
    step: 'Synthetic profile reviewed',
    used,
    inferred,
    requiresHumanReview,
    output,
  },
];

export const syntheticLeads: SyntheticLead[] = [
  {
    id: 'brightpath-dental',
    companyName: 'BrightPath Dental Group',
    industry: 'Healthcare services',
    region: 'Southeast United States',
    employeeCount: 180,
    summary: 'Fictitious multi-location dental services group with centralized intake and office-level follow-up workflows.',
    painSignals: ['Split lead intake across phone, web forms, and callbacks.', 'Handoff friction between central operations and local offices.', 'Revenue depends on fast response and consistent follow-up.'],
    buyingSignals: ['Recent expansion into additional markets.', 'Centralized operations model.', 'Clear response-time value.'],
    possibleUseCases: ['Inquiry triage', 'CRM note standardization', 'Follow-up readiness checklist'],
    aiResearchSummary: 'Simulated AI summary: BrightPath looks like a strong fit because it has enough operational scale, repeatable intake workflows, and clear revenue impact from faster review and cleaner handoffs.',
    fitScore: 88,
    confidenceScore: 82,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Confirm whether intake data is centralized before assuming CRM improvement scope.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: validate intake workflow and CRM ownership.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 19, painPointFit: 22, buyingSignalFit: 21, operationalComplexity: 13, riskPenalty: -5 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'Healthcare services / multi-location SMB',
      suggestedNextStep: 'Validate intake workflow and CRM ownership.',
      summaryForCrm: 'Synthetic high-fit lead with likely intake routing and CRM handoff friction. Strong candidate for human-reviewed AI workflow discovery.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Industry', 'employee count', 'multi-location model'], ['Likely intake routing friction'], ['Centralized CRM ownership'], 'High Fit with 88 fit score and 82 confidence score.'),
  },
  {
    id: 'harborpoint-manufacturing',
    companyName: 'HarborPoint Manufacturing',
    industry: 'Specialty manufacturing',
    region: 'Midwest United States',
    employeeCount: 210,
    summary: 'Fictitious specialty manufacturer with custom quote requests and engineering review before sales follow-up.',
    painSignals: ['Custom requests need manual review before qualification.', 'Sales and engineering handoffs slow quote readiness.', 'Technical resources can be pulled into weak-fit opportunities.'],
    buyingSignals: ['High-friction quoting workflow.', 'Cross-functional qualification.', 'Need for structured CRM notes.'],
    possibleUseCases: ['Quote-intake classification', 'Technical-fit triage', 'CRM-ready qualification summary'],
    aiResearchSummary: 'Simulated AI summary: HarborPoint is a strong fit because custom manufacturing inquiries often require structured triage before sales or engineering time is used.',
    fitScore: 91,
    confidenceScore: 78,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Data Gap', text: 'The demo profile does not confirm current CRM or quote-management tools.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: validate quoting bottleneck before recommending use case.',
    scoringBreakdown: { industryFit: 20, companySizeFit: 20, painPointFit: 24, buyingSignalFit: 22, operationalComplexity: 14, riskPenalty: -9 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'Specialty manufacturing / quote-heavy SMB',
      suggestedNextStep: 'Review quoting workflow and sales-engineering handoff process.',
      summaryForCrm: 'Synthetic high-fit manufacturing lead with likely quote triage and technical review friction.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Custom quote context', 'employee count', 'sales-engineering handoff clue'], ['Manual qualification likely consumes technical staff time'], ['Current quoting process and CRM fields'], 'Lead advanced to high-fit scoring review.'),
  },
  {
    id: 'sunriver-home-services',
    companyName: 'SunRiver Home Services',
    industry: 'Home services',
    region: 'Florida',
    employeeCount: 95,
    summary: 'Fictitious regional home-services company with field teams, inbound service requests, and seasonal demand spikes.',
    painSignals: ['Volume spikes make manual inquiry prioritization difficult.', 'Dispatch and sales follow-up compete for attention.', 'Slow follow-up can directly affect revenue.'],
    buyingSignals: ['Regional scale above owner-operator stage.', 'Repeatable inquiry qualification workflow.', 'Clear business value from faster response.'],
    possibleUseCases: ['Service-request triage', 'Lead urgency scoring', 'CRM handoff summary'],
    aiResearchSummary: 'Simulated AI summary: SunRiver appears to be a good fit because urgency, geography, and job type likely affect lead priority.',
    fitScore: 81,
    confidenceScore: 74,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Weak Signal', text: 'Lead volume is inferred from company type and size, not confirmed.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm inquiry volume and seasonality.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 17, painPointFit: 20, buyingSignalFit: 18, operationalComplexity: 11, riskPenalty: -3 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'Home services / regional operator',
      suggestedNextStep: 'Validate inbound lead volume and dispatch handoff process.',
      summaryForCrm: 'Synthetic high-fit home-services lead with likely inquiry prioritization and response-time opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Home services category', 'regional operating model', '95 employees'], ['Seasonal lead-volume spikes'], ['Actual inbound volume and dispatch process'], 'Lead scored as high fit with moderate confidence.'),
  },
  {
    id: 'northstar-logistics',
    companyName: 'Northstar Logistics Partners',
    industry: 'Logistics services',
    region: 'United States / Philippines support desk',
    employeeCount: 240,
    summary: 'Fictitious logistics services company with distributed operations and internal support coordination across time zones.',
    painSignals: ['Distributed teams may create inconsistent CRM notes.', 'Operational exceptions distract sales and account teams.', 'Lead and account context may be fragmented across systems.'],
    buyingSignals: ['Cross-time-zone support model.', 'Operational complexity creates need for structured summaries.', 'Potential value from cleaner qualification and handoffs.'],
    possibleUseCases: ['Lead-to-account context summary', 'Internal handoff assistant', 'CRM field completion support'],
    aiResearchSummary: 'Simulated AI summary: Northstar is a medium fit because the strongest use case may be CRM readiness and internal context capture rather than pure lead qualification.',
    fitScore: 76,
    confidenceScore: 68,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'ICP Mismatch', text: 'The strongest use case may be internal handoff improvement rather than lead qualification.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: clarify whether revenue or operations owns the problem.',
    scoringBreakdown: { industryFit: 13, companySizeFit: 20, painPointFit: 19, buyingSignalFit: 16, operationalComplexity: 15, riskPenalty: -7 },
    crmPreview: {
      leadStatus: 'Hold',
      suggestedSegment: 'Logistics / distributed operations',
      suggestedNextStep: 'Clarify whether need is lead qualification, CRM hygiene, or operations handoff.',
      summaryForCrm: 'Synthetic medium-fit lead. Distributed operations suggest workflow friction, but use case ownership requires human review.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Distributed support model', 'employee count', 'operations context'], ['CRM and handoff friction'], ['Revenue owner versus operations owner'], 'Lead placed on Hold pending human review.'),
  },
  {
    id: 'clearwater-senior-care',
    companyName: 'Clearwater Senior Care Network',
    industry: 'Healthcare services',
    region: 'Carolinas',
    employeeCount: 155,
    summary: 'Fictitious senior-care provider network with family inquiries, intake qualification, and location-level admissions follow-up.',
    painSignals: ['Inquiry quality varies by location.', 'Family intake requires careful handoff notes.', 'Delayed follow-up can affect admissions conversion.'],
    buyingSignals: ['Multi-site care model.', 'High-value intake workflow.', 'Need for consistent handoff documentation.'],
    possibleUseCases: ['Intake summary generation', 'Location routing guidance', 'CRM-ready admission notes'],
    aiResearchSummary: 'Simulated AI summary: Clearwater is a strong fit because inquiry quality, urgency, and location routing create a practical human-reviewed qualification use case.',
    fitScore: 86,
    confidenceScore: 76,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Healthcare-adjacent workflows require confirmation of privacy and compliance boundaries.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm privacy boundaries and intake ownership.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 18, painPointFit: 22, buyingSignalFit: 20, operationalComplexity: 13, riskPenalty: -5 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'Healthcare services / care network',
      suggestedNextStep: 'Validate intake volume, privacy requirements, and admissions handoff process.',
      summaryForCrm: 'Synthetic high-fit care-network lead with likely intake routing and admissions handoff opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Care network model', 'employee count', 'intake context'], ['Inquiry routing and admission handoff friction'], ['Privacy boundaries and intake systems'], 'Lead scored High Fit with compliance review flag.'),
  },
  {
    id: 'bluepeak-managed-services',
    companyName: 'BluePeak Managed Services',
    industry: 'Managed services',
    region: 'Texas',
    employeeCount: 130,
    summary: 'Fictitious managed services firm with inbound support requests, sales discovery calls, and account expansion opportunities.',
    painSignals: ['Sales and support signals may live in separate systems.', 'Discovery notes may not consistently reach CRM.', 'Follow-up quality affects expansion opportunities.'],
    buyingSignals: ['Service desk and revenue handoff overlap.', 'Likely CRM hygiene pressure.', 'Repeatable qualification and account review workflow.'],
    possibleUseCases: ['Call summary to CRM', 'Expansion signal scoring', 'Support-to-sales handoff notes'],
    aiResearchSummary: 'Simulated AI summary: BluePeak is a strong fit because managed services firms often need cleaner handoffs between support, account management, and sales.',
    fitScore: 84,
    confidenceScore: 80,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Weak Signal', text: 'Exact CRM and ticketing tools are not confirmed in the synthetic profile.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm CRM and ticketing workflow before export.',
    scoringBreakdown: { industryFit: 20, companySizeFit: 18, painPointFit: 20, buyingSignalFit: 19, operationalComplexity: 11, riskPenalty: -4 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'Managed services / support-to-sales workflow',
      suggestedNextStep: 'Validate CRM, ticketing, and account-management handoff process.',
      summaryForCrm: 'Synthetic high-fit managed-services lead with likely support-to-sales handoff and CRM hygiene opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Managed services category', 'support and sales context'], ['Support-to-sales handoff friction'], ['Current CRM and ticketing tools'], 'Lead scored High Fit for revenue-workflow review.'),
  },
  {
    id: 'summit-trade-supply',
    companyName: 'Summit Trade Supply',
    industry: 'B2B distribution',
    region: 'Mountain West',
    employeeCount: 115,
    summary: 'Fictitious B2B trade supplier with contractor accounts, quote requests, and recurring reorders.',
    painSignals: ['Quote requests may arrive with incomplete job context.', 'Account history may not be visible during qualification.', 'Sales follow-up depends on clean product and job notes.'],
    buyingSignals: ['B2B account workflow.', 'Repeat quote and reorder activity.', 'Clear value from CRM-ready summaries.'],
    possibleUseCases: ['Quote request summarization', 'Account context lookup', 'CRM-ready next-step notes'],
    aiResearchSummary: 'Simulated AI summary: Summit is a strong fit because distribution workflows often benefit from faster quote triage and better account-context handoffs.',
    fitScore: 83,
    confidenceScore: 73,
    scoreBand: 'High Fit',
    riskFlags: [{ severity: 'Low', category: 'Data Gap', text: 'Current quote-management process is not confirmed.' }],
    recommendedAction: 'Qualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: verify quote volume and account-history process.',
    scoringBreakdown: { industryFit: 18, companySizeFit: 18, painPointFit: 20, buyingSignalFit: 19, operationalComplexity: 12, riskPenalty: -4 },
    crmPreview: {
      leadStatus: 'Research Qualified',
      suggestedSegment: 'B2B distribution / quote-heavy workflow',
      suggestedNextStep: 'Validate quote intake volume and account-history access.',
      summaryForCrm: 'Synthetic high-fit distribution lead with likely quote triage and account-context opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['B2B distribution model', 'quote request context'], ['Incomplete quote data and account context gaps'], ['Quote volume and CRM usage'], 'Lead scored High Fit for quote-preparation workflow.'),
  },
  {
    id: 'cedarworks-construction',
    companyName: 'CedarWorks Construction',
    industry: 'Construction services',
    region: 'Georgia',
    employeeCount: 140,
    summary: 'Fictitious construction services firm with project inquiries, bid qualification, and field-office coordination.',
    painSignals: ['Project inquiries need fast fit checks.', 'Bid notes may be inconsistent across offices.', 'Field and sales teams may duplicate qualification work.'],
    buyingSignals: ['Project-based sales workflow.', 'Multi-office coordination.', 'Need for consistent qualification criteria.'],
    possibleUseCases: ['Project-fit scoring', 'Bid intake summary', 'CRM handoff checklist'],
    aiResearchSummary: 'Simulated AI summary: CedarWorks is a medium fit because bid qualification is useful, but the workflow may require more industry-specific scoping before implementation.',
    fitScore: 72,
    confidenceScore: 66,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'Human Review Required', text: 'Construction bidding workflows may need more detailed process mapping before qualification.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: confirm bid workflow and project-fit criteria.',
    scoringBreakdown: { industryFit: 12, companySizeFit: 18, painPointFit: 18, buyingSignalFit: 16, operationalComplexity: 13, riskPenalty: -5 },
    crmPreview: {
      leadStatus: 'Hold',
      suggestedSegment: 'Construction services / bid qualification',
      suggestedNextStep: 'Clarify bid intake workflow and qualification criteria before export.',
      summaryForCrm: 'Synthetic medium-fit construction lead with possible bid intake and CRM handoff opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Project inquiry model', 'multi-office context'], ['Bid qualification friction'], ['Bid process and project-fit fields'], 'Lead placed on Hold pending workflow review.'),
  },
  {
    id: 'orchid-valley-hospitality',
    companyName: 'Orchid Valley Hospitality',
    industry: 'Hospitality services',
    region: 'Nevada',
    employeeCount: 185,
    summary: 'Fictitious hospitality group with event inquiries, group bookings, and location-specific sales follow-up.',
    painSignals: ['Group inquiries need routing and prioritization.', 'Event details may be incomplete at intake.', 'Local teams may follow up inconsistently.'],
    buyingSignals: ['Multi-location service model.', 'High-value inquiry workflow.', 'Clear human-review need before outreach.'],
    possibleUseCases: ['Event inquiry scoring', 'Location routing support', 'CRM-ready booking summary'],
    aiResearchSummary: 'Simulated AI summary: Orchid Valley is a medium fit because the workflow has revenue value, but the use case may sit outside the highest-priority ICP industries.',
    fitScore: 69,
    confidenceScore: 69,
    scoreBand: 'Medium Fit',
    riskFlags: [{ severity: 'Medium', category: 'ICP Mismatch', text: 'Hospitality is adjacent to the ICP but not one of the top target industries.' }],
    recommendedAction: 'Hold',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: decide whether hospitality belongs in this ICP for the demo.',
    scoringBreakdown: { industryFit: 10, companySizeFit: 19, painPointFit: 17, buyingSignalFit: 17, operationalComplexity: 12, riskPenalty: -6 },
    crmPreview: {
      leadStatus: 'Hold',
      suggestedSegment: 'Hospitality / event inquiry workflow',
      suggestedNextStep: 'Confirm ICP fit before moving to CRM export preview.',
      summaryForCrm: 'Synthetic medium-fit hospitality lead with possible event inquiry and routing opportunity.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['Hospitality event inquiry model', 'employee count'], ['Group booking routing friction'], ['ICP fit decision'], 'Lead placed on Hold due to ICP-adjacent status.'),
  },
  {
    id: 'evergreen-specialty-foods',
    companyName: 'Evergreen Specialty Foods',
    industry: 'Specialty foods distribution',
    region: 'Pacific Northwest',
    employeeCount: 65,
    summary: 'Fictitious specialty foods distributor with a smaller team and mixed retail, wholesale, and hospitality customers.',
    painSignals: ['Customer segments may require different qualification paths.', 'Order and lead data may be spread across simple tools.', 'Smaller team may have limited bandwidth for process change.'],
    buyingSignals: ['Possible need for customer segmentation.', 'Repeatable qualification could help if volume is high enough.'],
    possibleUseCases: ['Customer-segment classification', 'Inquiry summary drafting', 'Manual CRM cleanup checklist'],
    aiResearchSummary: 'Simulated AI summary: Evergreen may benefit from AI-assisted classification, but it is below the preferred employee-size range.',
    fitScore: 58,
    confidenceScore: 70,
    scoreBand: 'Low Fit',
    riskFlags: [{ severity: 'High', category: 'ICP Mismatch', text: 'Company size is below the preferred ICP range for this demo workflow.' }],
    recommendedAction: 'Disqualified',
    reviewStatus: 'Needs Review',
    reviewerNotes: 'Human review: likely too small unless lead volume is unusually high.',
    scoringBreakdown: { industryFit: 13, companySizeFit: 7, painPointFit: 14, buyingSignalFit: 12, operationalComplexity: 8, riskPenalty: -6 },
    crmPreview: {
      leadStatus: 'Disqualified',
      suggestedSegment: 'Specialty distribution / below-size ICP',
      suggestedNextStep: 'Do not export unless human reviewer confirms unusual volume or strategic fit.',
      summaryForCrm: 'Synthetic low-fit lead. Potential workflow need exists, but company size appears below preferred ICP for this portfolio demo.',
      humanReviewRequired: true,
    },
    auditTrail: makeTrail(['65 employee count', 'mixed customer base'], ['Limited scale for full workflow implementation'], ['Actual lead volume'], 'Lead marked Low Fit and recommended for disqualification.'),
  },
];
